query onboarding{
  kits{
    id,
    title,
    taskSet{
      id,
      name,
      description
    }
    sessionSet{
      id,
      user{
        username
      },
      buddy{
        username
      },
      completed,
      progressSet{
        task{
          id
        },
        completed
      },
      kit{
        id,
        title
      }
    }
  }
}
