query goals{
  goals{
    id,
    title,
    description,
    start,
    end,
    completed,
    published,
    kpiSet{
      id,
      metric,
      target,
      current,
      change,
      kpiupdateSet{
        progress,
        created,
      }
    }
    team{
      id
    },
    user{
      username
    },
    parent{
      id
    }
  }
}
