query organisations{
    organisations{
      name,
      website,
      branches,
      cfFrequency,
      levelSet{
        id,
        label,
        number,
        teamSet{
          id
          name,
          parent{
            id
          },
          active,
          positionSet{
            id,
            title,
            userpositionSet{
              user{
                id,
                username,
                firstName,
                lastName,
                email
              }
            }
          }
        }
      }
    }
}
